# Generated by Django 3.0.7 on 2020-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNo', models.CharField(max_length=10)),
                ('Class', models.IntegerField()),
                ('father', models.CharField(max_length=120)),
                ('mobileNo', models.CharField(max_length=10)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
    ]
