# Generated by Django 3.0.7 on 2020-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0003_auto_20200627_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
