# Generated by Django 3.0.7 on 2020-06-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchool', '0004_studentfees_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='complete',
        ),
        migrations.AddField(
            model_name='studentfees',
            name='roll',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
